name: C Programs Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install GCC
      run: sudo apt-get install -y gcc

    - name: Compile add.c
      run: gcc -o add TESTTEST/Add.c

    - name: Compile multiply_by_10.c
      run: gcc -o multiply_by_10 TESTTEST/MulTen.c

    - name: Test add.c
      run: echo "3 7" | ./add | grep -q "10"

    - name: Test multiply_by_10.c
      run: echo "5" | ./multiply_by_10 | grep -q "50"
